const musicTwt = [
  {
    id: 1,
    name: "JKT48",
    title: "Angin Kita",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Angin Kita.mp3",
  },
  {
    id: 2,
    name: "JKT48",
    title: "Mango No.2",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Mango No. 2.mp3",
  },
  {
    id: 3,
    name: "JKT48",
    title: "Sambil Menggandeng Erat Tanganku",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Sambil Menggandeng Erat Tanganku.mp3",
  },
  {
    id: 4,
    name: "JKT48",
    title: "Bel Sekolah Adalah Love Song",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Bel Sekolah adalah Love Song.mp3",
  },
  {
    id: 5,
    name: "JKT48",
    title: "Glory days",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Glory Days.mp3",
  },
  {
    id: 6,
    name: "JKT48",
    title: "Barcode",
    image: "../assets/images/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Barcode.mp3",
  },
  {
    id: 7,
    name: "JKT48",
    title: "ajak aku pergi menuju ke wimbledo",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Ajak Aku Pergi Menuju ke Wimbledo.mp3",
  },
  {
    id: 8,
    name: "JKT48",
    title: "Sang Pianis Hujan",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Sang Pianis Hujan.mp3",
  },
  {
    id: 9,
    name: "JKT48",
    title: "Keberadaan Coklat Itu",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Keberadaan Coklat Itu.mp3",
  },
  {
    id: 10,
    name: "JKT48",
    title: "Innocence",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Innocence.mp3",
  },
  {
    id: 11,
    name: "JKT48",
    title: "Romance Rocket",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Romance Rocket.mp3",
  },
  {
    id: 12,
    name: "JKT48",
    title: "Arah Sang Cinta Dan Balasannya",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Arah Sang Cinta dan Balasannya.mp3",
  },
  {
    id: 13,
    name: "JKT48",
    title: "Aku Sangat Suka",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Aku Sangat Suka.mp3",
  },
  {
    id: 14,
    name: "JKT48",
    title: "Tali Persahabatan",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Tali Persahabatan.mp3",
  },
  {
    id: 15,
    name: "JKT48",
    title: "Malam Hari Selasa",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Malam Hari Selasa.mp3",
  },
  {
    id: 16,
    name: "JKT48",
    title: "Di Tempat Yang Jauh Pun",
    image: "../assets/images/jkt48/twt.jpg",
    music: "../assets/songs/tewotsuinagara/Di Tempat yang Jauh pun.mp3",
  },
];
