const newMusicJkt48 = [
  {
    id: 1,
    name: "JKT48",
    title: "After Rain",
    image: "../assets/images/jkt48/after rain.jpeg",
    music: "../assets/songs/jkt48/JKT48 - After Rain .mp3",
  },
  {
    id: 2,
    name: "JKT48",
    title: "Alasanku Maybe",
    image: "../assets/images/jkt48/alasanku maybe.jpg",
    music: "../assets/songs/jkt48/Alasanku MAYBE - JKT48.mp3",
  },

  {
    id: 3,
    name: "JKT48",
    title: "Apakah Kau Melihat Mentari Senja",
    image: "../assets/images/jkt48/boku no taiyo.jpg",
    music: "../assets/songs/jkt48/ Apakah Kau Melihat Mentari Senja - JKT48.mp3",
  },

  {
    id: 4,
    name: "JKT48",
    title: "Baby_Baby_Baby",
    image: "../assets/images/jkt48/Heavy Rotation.jpg",
    music: "../assets/songs/jkt48/Baby_Baby_Baby.mp3",
  },

  {
    id: 5,
    name: "JKT48",
    title: "Back Hip Circle",
    image: "../assets/images/jkt48/saka agari.jpg",
    music: "../assets/songs/jkt48/Back Hip Circle .mp3",
  },
  {
    id: 6,
    name: "JKT48",
    title: "Beginner",
    image: "../assets/images/jkt48/JKT48_Beginner_Regular.jpg",
    music: "../assets/songs/jkt48/Beginner - JKT48 .mp3",
  },
  {
    id: 7,
    name: "JKT48",
    title: "Bersama Kamu, Pelangi Dan Mentari",
    image: "../assets/images/jkt48/alasanku maybe.jpg",
    music: "../assets/songs/jkt48/Bersama Kamu, Pelangi Dan Mentari JKT48.mp3",
  },
  {
    id: 8,
    name: "JKT48",
    title: "Bunga Matahari",
    image: "../assets/images/jkt48/boku no taiyo.jpg",
    music: "../assets/songs/jkt48/Bunga Matahari .mp3",
  },

  {
    id: 9,
    name: "JKT48",
    title: "Cinta Pertama di Jam 7 Lewat 12",
    image: "../assets/images/jkt48/cinta pertama di jam 7.jpeg",
    music: "../assets/songs/jkt48/JKT48 - Cinta Pertama di Jam 7 Lewat 12.mp3",
  },
  {
    id: 10,
    name: "JKT48",
    title: "Eien Pressure",
    image: "../assets/images/jkt48/eien pressure.jpg",
    music: "../assets/songs/jkt48/Eien Pressure JKT48.mp3",
  },
  {
    id: 11,
    name: "JKT48",
    title: "Everyday, Kachuusha",
    image: "../assets/images/jkt48/everyday kachuusha.jpeg",
    music: "../assets/songs/jkt48/Everyday, Kachuusha.mp3",
  },
  {
    id: 12,
    name: "JKT48",
    title: "First Rabbit",
    image: "../assets/images/jkt48/alasanku maybe.jpg",
    music: "../assets/songs/jkt48/ First Rabbit JKT48.mp3",
  },
  {
    id: 13,
    name: "JKT48",
    title: "Fortune Cookie in Love",
    image: "../assets/images/jkt48/kfc.jpeg",
    music: "../assets/songs/jkt48/Fortune Cookie in Love.mp3",
  },
  {
    id: 14,
    name: "JKT48",
    title: "Gingham Check",
    image: "../assets/images/jkt48/gingham check.jpg",
    music: "../assets/songs/jkt48/Gingham Check .mp3",
  },

  {
    id: 15,
    name: "JKT48",
    title: "Gonna Jump",
    image: "../assets/images/jkt48/believe.jpeg",
    music: "../assets/songs/jkt48/JKT48 - Gonna Jump.mp3",
  },
  {
    id: 16,
    name: "JKT48",
    title: "Hanya Lihat Ke Depan",
    image: "../assets/images/jkt48/597px-Cover_mae_shika.jpg",
    music: "../assets/songs/jkt48/Hanya Lihat Ke Depan  JKT48.mp3",
  },
  {
    id: 17,
    name: "JKT48",
    title: "Heavy Rotation",
    image: "../assets/images/jkt48/Heavy Rotation.jpg",
    music: "../assets/songs/jkt48/Heavy Rotation .mp3",
  },
  {
    id: 18,
    name: "JKT48",
    title: "Honest Man",
    image: "../assets/images/jkt48/dewi theater.jpeg",
    music: "../assets/songs/jkt48/Honest Man.mp3",
  },

  {
    id: 19,
    name: "JKT48",
    title: "Indahnya Senyum Manismu",
    image: "../assets/images/jkt48/indahnya senyum manismu.jpg",
    music: "../assets/songs/jkt48/JKT48 Indahnya Senyum Manismu.mp3",
  },

  {
    id: 20,
    name: "JKT48",
    title: "Kalender yang Dipercepat",
    image: "../assets/images/jkt48/kalender yang dipercepat.jpeg",
    music: "../assets/songs/jkt48/Kalender yang Dipercepat.mp3",
  },

  {
    id: 21,
    name: "JKT48",
    title: "Karena Kusuka Dirimu",
    image: "../assets/images/jkt48/Heavy Rotation.jpg",
    music: "../assets/songs/jkt48/Karena Kusuka Dirimu.mp3",
  },

  {
    id: 22,
    name: "JKT48",
    title: "Maafkan, Summer",
    image: "../assets/images/jkt48/Heavy Rotation.jpg",
    music: "../assets/songs/jkt48/Maafkan, Summer .mp3",
  },
  {
    id: 23,
    name: "JKT48",
    title: "Matahari Milikku",
    image: "../assets/images/jkt48/boku no taiyo.jpg",
    music: "../assets/songs/jkt48/Matahari Milikku.mp3",
  },
  {
    id: 24,
    name: "JKT48",
    title: "Manatsu no Sounds Good",
    image: "../assets/images/jkt48/JKT48_Manatsu_no_Sounds_Good.jpg",
    music: "../assets/songs/jkt48/[MV] Manatsu no Sounds Good .mp3",
  },
  {
    id: 25,
    name: "JKT48",
    title: "Only Today",
    image: "../assets/images/jkt48/alasanku maybe.jpg",
    music: "../assets/songs/jkt48/JKT48 - Only Today.mp3",
  },
  {
    id: 26,
    name: "JKT48",
    title: "Papan Penanda Isi Hati",
    image: "../assets/images/jkt48/JKT48_-_Kokoro_no_Placard.jpg",
    music: "../assets/songs/jkt48/JKT48 - Papan Penanda Isi Hati.mp3",
  },
  {
    id: 27,
    name: "JKT48",
    title: "Pareo adalah Emerald",
    image: "../assets/images/jkt48/220px-JKT48-Pareo-regular.jpg",
    music: "../assets/songs/jkt48/JKT48 - Pareo adalah Emerald.mp3",
  },

  {
    id: 28,
    name: "JKT48",
    title: "Pesawat Kertas 365 Hari",
    image: "../assets/images/jkt48/alasanku maybe.jpg",
    music: "../assets/songs/jkt48/Pesawat Kertas 365 Hari  JKT48.mp3",
  },

  {
    id: 29,
    name: "JKT48",
    title: "Ponytail Dan Shu-Shu",
    image: "../assets/images/jkt48/Heavy Rotation.jpg",
    music: "../assets/songs/jkt48/Ponytail Dan Shu-Shu.mp3",
  },

  {
    id: 30,
    name: "JKT48",
    title: "Rapsodi",
    image: "../assets/images/jkt48/JKT48_-_Rapsodi.jpg",
    music: "../assets/songs/jkt48/Rapsodi.mp3",
  },
  {
    id: 31,
    name: "JKT48",
    title: "Refrain Penuh Harapan",
    image: "../assets/images/jkt48/KiboutekiJKT.jpg",
    music: "../assets/songs/jkt48/Refrain Penuh Harapan JKT48.mp3",
  },
  {
    id: 32,
    name: "JKT48",
    title: "River",
    image: "../assets/images/jkt48/JKT48River.jpg",
    music: "../assets/songs/jkt48/River.mp3",
  },
  {
    id: 33,
    name: "JKT48",
    title: "RUN RUN RUN",
    image: "../assets/images/jkt48/boku no taiyo.jpg",
    music: "../assets/songs/jkt48/RUN RUN RUN.mp3",
  },
  {
    id: 34,
    name: "JKT48",
    title: "Salah Dengar Rock",
    image: "../assets/images/jkt48/believe.jpeg",
    music: "../assets/songs/jkt48/JKT48 - Salah Dengar Rock.mp3",
  },

  {
    id: 35,
    name: "JKT48",
    title: "Seesaw Game Penuh Air Mata",
    image: "../assets/images/jkt48/everyday kachuusha.jpeg",
    music: "../assets/songs/jkt48/Seesaw Game Penuh Air Mata.mp3",
  },
  {
    id: 36,
    name: "JKT48",
    title: "Simpati Gravitasi",
    image: "../assets/images/jkt48/eien pressure.jpg",
    music: "../assets/songs/jkt48/Simpati Gravitasi.mp3",
  },
  {
    id: 37,
    name: "JKT48",
    title: "TSUGI NO SEASON",
    image: "../assets/images/jkt48/tsugi no season.jpg",
    music: "../assets/songs/jkt48/JKT48 - TSUGI NO SEASON.mp3",
  },

  {
    id: 38,
    name: "JKT48",
    title: "UZA",
    image: "../assets/images/jkt48/uza.jpeg",
    music: "../assets/songs/jkt48/UZA.mp3",
  },
];
