const musicPajama = [
  {
    id: 1,
    name: 'JKT48',
    title: 'Hari Pertama',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Hari Pertama.mp3',
  },
  {
    id: 2,
    name: 'JKT48',
    title: 'Jurus Rahasia Teleport',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Jurus Rahasia Teleport.mp3',
  },
  {
    id: 3,
    name: 'JKT48',
    title: 'Putri Duyung Yang Sedang Sedih',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Putri Duyung yang Sedang Sedih.mp3',
  },
  {
    id: 4,
    name: 'JKT48',
    title: 'Bersepeda Berdua',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/JKT48 - Bersepeda Berdua.mp3',
  },
  {
    id: 5,
    name: 'JKT48',
    title: 'Ekor Malaikat',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Ekor Malaikat.mp3',
  },
  {
    id: 6,
    name: 'JKT48',
    title: 'Pajama Drive',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Pajama Drive.mp3',
  },
  {
    id: 7,
    name: 'JKT48',
    title: 'Prinsip Kesucian Hati',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Prinsip Kesucian Hati.mp3',
  },
  {
    id: 8,
    name: 'JKT48',
    title: 'Air Mata Perasaan Yang Tak Tersampaikan',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/air mata perasaan yang tak tersampaikan jkt48.mp3',
  },
  {
    id: 9,
    name: 'JKT48',
    title: 'Joan of Arc di Dalam Cermin',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Joan of Arc di Dalam Cermin.mp3',
  },
  {
    id: 10,
    name: 'JKT48',
    title: 'Two years Later',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Two years Later.mp3',
  },
  {
    id: 11,
    name: 'JKT48',
    title: 'Cara Menggunakan Hidup',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Cara Menggunakan Hidup.mp3',
  },
  {
    id: 12,
    name: 'JKT48',
    title: 'Rugi Sudah dicium',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Rugi Sudah dicium.mp3',
  },
  {
    id: 13,
    name: 'JKT48',
    title: 'Bunga Sakuraku',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Bunga Sakuraku.mp3',
  },
  {
    id: 14,
    name: 'JKT48',
    title: 'Wasshoi J!',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Wasshoi J!.mp3',
  },
  {
    id: 15,
    name: 'JKT48',
    title: 'Pelaut yang Melihat Mimpi di Tengah Badai',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Pelaut yang Melihat Mimpi di Tengah Badai.mp3',
  },
  {
    id: 16,
    name: 'JKT48',
    title: 'Baju Putih',
    image: '/assets/images/pajama.jpg',
    music: '/assets/songs/pajamadrive/Baju Putih.mp3',
  },
];

const musicRkj = [
  {
    id: 1,
    name: 'JKT48',
    title: 'Cahaya Panjang',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Cahaya Panjang.mp3',
  },
  {
    id: 2,
    name: 'JKT48',
    title: 'Di Tengah Hujan Badai Tiba',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Di Tengah Hujan Badai Tiba.mp3',
  },
  {
    id: 3,
    name: 'JKT48',
    title: 'Gadis SMA Putri Tidur',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Gadis SMA Putri Tidur.mp3',
  },
  {
    id: 4,
    name: 'JKT48',
    title: 'Jatuh Cinta Setiap Bertemu',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Kimi Ni Au Tabi Koi Wo Suru (Jatuh Cinta Setiap Bertemu Denganmu).mp3',
  },
  {
    id: 5,
    name: 'JKT48',
    title: 'Malaikat Hitam',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/JKT48 - Malaikat Hitam (Kuroi Tenshi).mp3',
  },
  {
    id: 6,
    name: 'JKT48',
    title: 'Virus Tipe Hati',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Virus Tipe Hati.mp3',
  },
  {
    id: 7,
    name: 'JKT48',
    title: 'Aturan Anti Cinta',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Aturan Anti Cinta.mp3',
  },
  {
    id: 8,
    name: 'JKT48',
    title: 'Tsundere!',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Tsundere!.mp3',
  },
  {
    id: 9,
    name: 'JKT48',
    title: 'Mawar Natal Musim Panas',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/JKT48 - Mawar Natal Musim Panas (Manatsu no Christmas Rose).mp3',
  },
  {
    id: 10,
    name: 'JKT48',
    title: 'Switch',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Switch.mp3',
  },
  {
    id: 11,
    name: 'JKT48',
    title: '109 - MARUKYUU',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/109 - MARUKYUU.mp3',
  },
  {
    id: 12,
    name: 'JKT48',
    title: 'Jejak Awan Pesawat',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Jejak Awan Pesawat.mp3',
  },
  {
    id: 13,
    name: 'JKT48',
    title: 'Sneakers Waktu Itu',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Sneakers Waktu itu.mp3',
  },
  {
    id: 14,
    name: 'JKT48',
    title: 'JKT Datang',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/JKT Datang!.mp3',
  },
  {
    id: 15,
    name: 'JKT48',
    title: 'Nafas Dalam Air Mata',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Napas dalam Air Mata.mp3',
  },
  {
    id: 16,
    name: 'JKT48',
    title: 'Teriakan Berlian',
    image: '/assets/images/rkj.jpg',
    music: '/assets/songs/renaikinshijurei/Teriakan Berlian.mp3',
  },
];

const musicTwt = [
  {
    id: 1,
    name: 'JKT48',
    title: 'Angin Kita',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Angin Kita.mp3',
  },
  {
    id: 2,
    name: 'JKT48',
    title: 'Mango No.2',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Mango No. 2.mp3',
  },
  {
    id: 3,
    name: 'JKT48',
    title: 'Sambil Menggandeng Erat Tanganku',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Sambil Menggandeng Erat Tanganku.mp3',
  },
  {
    id: 4,
    name: 'JKT48',
    title: 'Bel Sekolah Adalah Love Song',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Bel Sekolah adalah Love Song.mp3',
  },
  {
    id: 5,
    name: 'JKT48',
    title: 'Glory days',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Glory Days.mp3',
  },
  {
    id: 6,
    name: 'JKT48',
    title: 'Barcode',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Barcode.mp3',
  },
  {
    id: 7,
    name: 'JKT48',
    title: 'ajak aku pergi menuju ke wimbledo',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Ajak Aku Pergi Menuju ke Wimbledo.mp3',
  },
  {
    id: 8,
    name: 'JKT48',
    title: 'Sang Pianis Hujan',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Sang Pianis Hujan.mp3',
  },
  {
    id: 9,
    name: 'JKT48',
    title: 'Keberadaan Coklat Itu',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Keberadaan Coklat Itu.mp3',
  },
  {
    id: 10,
    name: 'JKT48',
    title: 'Innocence',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Innocence.mp3',
  },
  {
    id: 11,
    name: 'JKT48',
    title: 'Romance Rocket',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Romance Rocket.mp3',
  },
  {
    id: 12,
    name: 'JKT48',
    title: 'Arah Sang Cinta Dan Balasannya',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Arah Sang Cinta dan Balasannya.mp3',
  },
  {
    id: 13,
    name: 'JKT48',
    title: 'Aku Sangat Suka',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Aku Sangat Suka.mp3',
  },
  {
    id: 14,
    name: 'JKT48',
    title: 'Tali Persahabatan',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Tali Persahabatan.mp3',
  },
  {
    id: 15,
    name: 'JKT48',
    title: 'Malam Hari Selasa',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Malam Hari Selasa.mp3',
  },
  {
    id: 16,
    name: 'JKT48',
    title: 'Di Tempat Yang Jauh Pun',
    image: '/assets/images/twt.jpg',
    music: '/assets/songs/tewotsuinagara/Di Tempat yang Jauh pun.mp3',
  },
];
