const musicPajama = [
  {
    id: 1,
    name: "JKT48",
    title: "Hari Pertama",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Hari Pertama.mp3",
  },
  {
    id: 2,
    name: "JKT48",
    title: "Jurus Rahasia Teleport",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Jurus Rahasia Teleport.mp3",
  },
  {
    id: 3,
    name: "JKT48",
    title: "Putri Duyung Yang Sedang Sedih",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Putri Duyung yang Sedang Sedih.mp3",
  },
  {
    id: 4,
    name: "JKT48",
    title: "Bersepeda Berdua",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/JKT48 - Bersepeda Berdua.mp3",
  },
  {
    id: 5,
    name: "JKT48",
    title: "Ekor Malaikat",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Ekor Malaikat.mp3",
  },
  {
    id: 6,
    name: "JKT48",
    title: "Pajama Drive",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Pajama Drive.mp3",
  },
  {
    id: 7,
    name: "JKT48",
    title: "Prinsip Kesucian Hati",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Prinsip Kesucian Hati.mp3",
  },
  {
    id: 8,
    name: "JKT48",
    title: "Air Mata Perasaan Yang Tak Tersampaikan",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/air mata perasaan yang tak tersampaikan jkt48.mp3",
  },
  {
    id: 9,
    name: "JKT48",
    title: "Joan of Arc di Dalam Cermin",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Joan of Arc di Dalam Cermin.mp3",
  },
  {
    id: 10,
    name: "JKT48",
    title: "Two years Later",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Two years Later.mp3",
  },
  {
    id: 11,
    name: "JKT48",
    title: "Cara Menggunakan Hidup",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Cara Menggunakan Hidup.mp3",
  },
  {
    id: 12,
    name: "JKT48",
    title: "Rugi Sudah dicium",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Rugi Sudah dicium.mp3",
  },
  {
    id: 13,
    name: "JKT48",
    title: "Bunga Sakuraku",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Bunga Sakuraku.mp3",
  },
  {
    id: 14,
    name: "JKT48",
    title: "Wasshoi J!",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Wasshoi J!.mp3",
  },
  {
    id: 15,
    name: "JKT48",
    title: "Pelaut yang Melihat Mimpi di Tengah Badai",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Pelaut yang Melihat Mimpi di Tengah Badai.mp3",
  },
  {
    id: 16,
    name: "JKT48",
    title: "Baju Putih",
    image: "../assets/images/jkt48/pajama.jpg",
    music: "../assets/songs/pajamadrive/Baju Putih.mp3",
  },
];
