const musicRkj = [
  {
    id: 1,
    name: "JKT48",
    title: "Cahaya Panjang",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Cahaya Panjang.mp3",
  },
  {
    id: 2,
    name: "JKT48",
    title: "Di Tengah Hujan Badai Tiba",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Di Tengah Hujan Badai Tiba.mp3",
  },
  {
    id: 3,
    name: "JKT48",
    title: "Gadis SMA Putri Tidur",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Gadis SMA Putri Tidur.mp3",
  },
  {
    id: 4,
    name: "JKT48",
    title: "Jatuh Cinta Setiap Bertemu",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Kimi Ni Au Tabi Koi Wo Suru (Jatuh Cinta Setiap Bertemu Denganmu).mp3",
  },
  {
    id: 5,
    name: "JKT48",
    title: "Malaikat Hitam",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/JKT48 - Malaikat Hitam (Kuroi Tenshi).mp3",
  },
  {
    id: 6,
    name: "JKT48",
    title: "Virus Tipe Hati",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Virus Tipe Hati.mp3",
  },
  {
    id: 7,
    name: "JKT48",
    title: "Aturan Anti Cinta",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Aturan Anti Cinta.mp3",
  },
  {
    id: 8,
    name: "JKT48",
    title: "Tsundere!",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Tsundere!.mp3",
  },
  {
    id: 9,
    name: "JKT48",
    title: "Mawar Natal Musim Panas",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/JKT48 - Mawar Natal Musim Panas (Manatsu no Christmas Rose).mp3",
  },
  {
    id: 10,
    name: "JKT48",
    title: "Switch",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Switch.mp3",
  },
  {
    id: 11,
    name: "JKT48",
    title: "109 - MARUKYUU",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/109 - MARUKYUU.mp3",
  },
  {
    id: 12,
    name: "JKT48",
    title: "Jejak Awan Pesawat",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Jejak Awan Pesawat.mp3",
  },
  {
    id: 13,
    name: "JKT48",
    title: "Sneakers Waktu Itu",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Sneakers Waktu itu.mp3",
  },
  {
    id: 14,
    name: "JKT48",
    title: "JKT Datang",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/JKT Datang!.mp3",
  },
  {
    id: 15,
    name: "JKT48",
    title: "Nafas Dalam Air Mata",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Napas dalam Air Mata.mp3",
  },
  {
    id: 16,
    name: "JKT48",
    title: "Teriakan Berlian",
    image: "../assets/images/jkt48/rkj.jpg",
    music: "../assets/songs/renaikinshijurei/Teriakan Berlian.mp3",
  },
];
