const musicLaruku = [
  {
    id: 1,
    name: "L'Arc～en～Ciel",
    title: "Anata",
    image: "../assets/images/laruku/anata.jpg",
    music: "../assets/songs/laruku/Anata.mp3",
  },
  {
    id: 2,
    name: "L'Arc～en～Ciel",
    title: "Hitomi No Jyunin",
    image: "../assets/images/laruku/hitomi no jyonin.jpg",
    music: "../assets/songs/laruku/Hitomi No Jyunin .mp3",
  },
  {
    id: 3,
    name: "L'Arc～en～Ciel",
    title: "Jiyuu Eno Shoutai",
    image: "../assets/images/laruku/jiyuu eno shoutai.jpeg",
    music: "../assets/songs/laruku/Jiyuu Eno Shoutai.mp3",
  },
  {
    id: 4,
    name: "L'Arc～en～Ciel",
    title: "Blurry Eyes",
    image: "../assets/images/laruku/blurry eyes.jpg",
    music: "../assets/songs/laruku/L'Arc～en～Ciel「Blurry Eyes.mp3",
  },
  {
    id: 5,
    name: "L'Arc～en～Ciel",
    title: "Driver's High",
    image: "../assets/images/laruku/driver high.jpg",
    music: "../assets/songs/laruku/L'Arc～en～Ciel「Driver's High.mp3",
  },
  {
    id: 6,
    name: "L'Arc～en～Ciel",
    album: "Clicked Singles Best 13",
    image: "../assets/images/laruku/flower.jpg",
    music: "../assets/songs/laruku/L'Arc～en～Ciel「flower.mp3",
  },
  {
    id: 7,
    name: "L'Arc～en～Ciel",
    title: "HONEY",
    image: "../assets/images/laruku/honey.jpg",
    music: "../assets/songs/laruku/L'Arc～en～Ciel「HONEY.mp3",
  },
  {
    id: 8,
    name: "L'Arc～en～Ciel",
    title: "Link",
    image: "../assets/images/laruku/link.jpg",
    music: "../assets/songs/laruku/L'Arc～en～Ciel「Link.mp3",
  },
  {
    id: 9,
    name: "L'Arc～en～Ciel",
    title: "My Heart Draws a Dream",
    image: "../assets/images/laruku/my heart draws a dream.jpg",
    music: "../assets/songs/laruku/L'Arc en Ciel -  My Heart Draws a Dream.mp3",
  },
  {
    id: 10,
    name: "L'Arc～en～Ciel",
    title: "New World",
    image: "../assets/images/laruku/new world.jpeg",
    music: "../assets/songs/laruku/L'Arc～en～Ciel「New World.mp3",
  },
  {
    id: 11,
    name: "L'Arc～en～Ciel",
    title: "READY STEADY GO.mp3",
    image: "../assets/images/laruku/anata.jpg",
    music: "../assets/songs/laruku/L'Arc～en～Ciel「READY STEADY GO.mp3",
  },
  {
    id: 12,
    name: "L'Arc～en～Ciel",
    title: "pieces",
    image: "../assets/images/laruku/pieces.jpg",
    music: "../assets/songs/laruku/Pieces.mp3",
  },
];
